### ISSUE TITLE
[bug] don't work on nvim v0.7.0

### ISSUE THREAD

**Issue by yyb196** [ShikChen/osc52.vim#2]
elaborate in here: https://github.com/neovim/neovim/issues/18168

**Comment by ShikChen** [comment]
Hi, thanks for reporting. Could you help check

1. Is it a Kitty specific issue?
2. Is tmux being used?
3. It looks like the default `$TERM` under Kitty is `xterm-kitty`, but it looks like you have `xterm-256color` from the feedback report. Is it expected?

**Comment by yyb196** [comment]
I use kitty ssh to remote node, then start tmux and nvim. when I use nvim-0.5.1, OSC52 works, but using the same environment only upgrade nvim to version 0.7.0, it doesn't work. 

Since nvim never had support OSC 52, what tick does osc52.vim use to make it work? maybe the trick isn't exist in nvim 0.7.0.

**Comment by yyb196** [comment]
closing ticket, since after I destroy the remote node and create a new one, I can't reproduce it, may be some config in previous node is the culprit.

**Comment by ShikChen** [comment]
Thanks for the update and glad that the issue is resolved :)
